version: '3'

services:
# Discovery service
  discovery-service-app:
    build: /discovery-service/.
    ports:
      - "8761:8761"

# Resource service
  resource-db:
    image: postgres
    container_name: "resource-postgre"
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resource-db

  resource-service-app:
    build: /resource-service/.
    ports:
      - "8080:8080"
    env_file:
      - resource-service/.env
    depends_on:
      - resource-db
      - discovery-service-app

# Song services
  song-db:
    image: postgres
    container_name: "song-postgre"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: song-db

  song-service-app1:
    build: /song-service/.
    ports:
      - "8081:8081"
    env_file:
      - song-service/.env
    depends_on:
      - song-db
      - discovery-service-app

  song-service-app2:
    build: /song-service/.
    ports:
      - "8082:8082"
    env_file:
      - song-service/.env
    depends_on:
      - song-db
      - discovery-service-app